### ISSUE TITLE
It's best to indicate that it only supports Linux.

### ISSUE THREAD

**Issue by Datou** [chaojie/ComfyUI-Open-Sora#1]
Colossalai is linux only.

**Comment by chaojie** [comment]
Can you test Windows again? I deleted colosalai in requirements.txt, it should not have been used in the code

**Comment by Datou** [comment]
> Can you test Windows again? I deleted colosalai in requirements.txt, it should not have been used in the code

Traceback (most recent call last):
  File "C:\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI\custom_nodes\ComfyUI-Open-Sora\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "C:\ComfyUI\custom_nodes\ComfyUI-Open-Sora\nodes.py", line 19, in <module>
    from opensora.datasets import get_image
  File "C:\Users\doggi\AppData\Local\Programs\Python\Python311\Lib\site-packages\opensora\__init__.py", line 3, in <module>
    from .models import *
  File "C:\Users\doggi\AppData\Local\Programs\Python\Python311\Lib\site-packages\opensora\models\__init__.py", line 1, in <module>
    from .dit import *
  File "C:\Users\doggi\AppData\Local\Programs\Python\Python311\Lib\site-packages\opensora\models\dit\__init__.py", line 1, in <module>
    from .dit import DiT, DiT_XL_2, DiT_XL_2x2
  File "C:\Users\doggi\AppData\Local\Programs\Python\Python311\Lib\site-packages\opensora\models\dit\dit.py", line 34, in <module>
    from opensora.utils.ckpt_utils import load_checkpoint
  File "C:\Users\doggi\AppData\Local\Programs\Python\Python311\Lib\site-packages\opensora\utils\ckpt_utils.py", line 8, in <module>
    import colossalai
ModuleNotFoundError: No module named 'colossalai'

Cannot import C:\ComfyUI\custom_nodes\ComfyUI-Open-Sora module for custom nodes: No module named 'colossalai'

**Comment by zmwv823** [comment]
> Can you test Windows again? I deleted colosalai in requirements.txt, it should not have been used in the code

Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Open-Sora\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Open-Sora\nodes.py", line 19, in <module>
    from opensora.datasets import get_image
ModuleNotFoundError: No module named 'opensora'
