### ISSUE TITLE
ModuleNotFoundError: No module named 'opensora'

### ISSUE THREAD

**Issue by solomon-s2020** [chaojie/ComfyUI-Open-Sora#5]
WARNING- Traceback (most recent call last):
  File "/root/ComfyUI/nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/ComfyUI/custom_nodes/ComfyUI-Open-Sora/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "/root/ComfyUI/custom_nodes/ComfyUI-Open-Sora/nodes.py", line 19, in <module>
    from opensora.datasets import get_image
ModuleNotFoundError: No module named 'opensora'

**Comment by kitty-jenkem** [comment]
Samesies. Exact same thing.
If I try to install opensora itself, I get some errors with cuda mismatch even if I force 12.1 vs 12.6
